name: Suggest an improvement
description: Share an idea for Drift.
title: "[Idea]: "
body:
  - type: textarea
    id: problem
    attributes:
      label: What are you trying to do?
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: How could Drift help?
    validations:
      required: true
